### ISSUE TITLE
Section 4 CNAME issue

### ISSUE THREAD

**Issue by sisyphushappy** [dwchiang/laravel-on-aws-ecs-workshops#1]
Hi Ernest,

I'm working through Section 4 of the workshop, and I'm having issue with ACM. 

When I `cdk deploy`,  the ACM certificate stays in the status `Pending validation`. Your instructions say the following...

```
When you see something like this and seem pending there, it's time to login your AWS Management Console > ACM to setup a CNAME record for your domain. Once you add the CNAME record, wait for couple minutes, the CDK script will continue if it detects the CNAME configuration is correct.
```
I might not be understanding your instructions correctly, but where do I add the CNAME record so that the status changes to `Issued` like in your screenshot? For reference, when I expand the certificate, AWS gives me this instruction for `mydomain.com` and `*.mydomain.com`:

```
 Add the following CNAME record to the DNS configuration for your domain. The procedure for adding CNAME records depends on your DNS service Provider. Learn more. 
``` 

I tried adding this record to my DNS service provider as you do later in the section with the ALB DNS, but I'm not sure if that's correct. Any additional clarity on this would be greatly appreciated!

**Comment by sisyphushappy** [comment]
I was able to get this to work by registering a domain in Route53. Not sure if there's some issue my DNS registrar.

**Comment by dwchiang** [comment]
Thanks for the input :) 

I will see if I can try to edit the instructions to be clearer.

**Comment by sisyphushappy** [comment]
Thank you for making this wonderful tutorial! Are you planning to add any further sections to it? If so, what functionalities will they encompass?

**Comment by dwchiang** [comment]
Thanks for the support 👍 

I am thinking some common scenarios when we are using Laravel in the daily operation, like CI/CD, access databases/cache, check logs, handling cron jobs/queue worker jobs, and having some benchmarks.

Please feel free to give me some inputs.

I hope to continue to have more sessions next month. (Too many todo items need to be closed by end of this year...><"

**Comment by sisyphushappy** [comment]
I think all your suggestions would be great, especially CI/CI (CodePipeline perhaps?); personally, I am new to Laravel so any documentation of common things related to daily operations / deployment infra is super useful.
